name = "cardano-foundation/signature-aggregation-case"
version = "0.1.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'cardano-foundation/signature-aggregation-case'"

[repository]
user = "cardano-foundation"
project = "signature-aggregation-case"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "ilap/bls"
version = "0.4.0"
source = "github"

[config]
